CREATE TABLE organizations (
	id int(11) NOT NULL AUTO_INCREMENT,
	name varchar(100) NOT NULL DEFAULT '',
	position varchar(50) NOT NULL DEFAULT '',
	organization_name varchar(100) NOT NULL DEFAULT '',
	organization_email varchar(50) NOT NULL DEFAULT '',
	address varchar(255) NOT NULL DEFAULT '',
	city varchar(50) NOT NULL DEFAULT '',
	region varchar(50) NOT NULL DEFAULT '',
	country varchar(50) NOT NULL DEFAULT '',
	zipcode varchar(50),
	website varchar(100),
	logo varchar(100),
	user_id int(11) NOT NULL,
	created_at datetime NOT NULL,
	updated_at datetime NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id) REFERENCES users (id),
	INDEX user_INDEX (user_id ASC)
)
